repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
      - id: end-of-file-fixer
  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        additional_dependencies: [toml]
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--config=.flake8']
        additional_dependencies:
        - 'flake8-docstrings'
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.7.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/jorgenusan/pydepcheck.git
    rev: v0.1.2
    hooks:
      - id: pydepcheck
        args: ['--env-file', 'requirements.txt', '--env-name', 'pydepcheck']
